version: "2"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: customer_server
    working_dir: /var/www/html
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
        - .:/var/www/html
    links: 
        - sql

  sql:
    image: mysql:8.0
    container_name: customer_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password  
